/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GhostFundDonationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addProject"
      | "calculateSealFee"
      | "donate"
      | "owner"
      | "projectCount"
      | "projects"
      | "renounceOwnership"
      | "sealContract"
      | "sealFeeFixed"
      | "sealFeePercent"
      | "transferOwnership"
      | "updateFees"
      | "useFixedFee"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationRecorded"
      | "OwnershipTransferred"
      | "ProjectAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSealFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sealContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sealFeeFixed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sealFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFees",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "useFixedFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateSealFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sealContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sealFeeFixed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sealFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "useFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace DonationRecordedEvent {
  export type InputTuple = [
    donor: AddressLike,
    projectId: BigNumberish,
    amount: BigNumberish,
    wantsSeal: boolean,
    sealFee: BigNumberish,
    timestamp: BigNumberish,
    sealTokenId: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    projectId: bigint,
    amount: bigint,
    wantsSeal: boolean,
    sealFee: bigint,
    timestamp: bigint,
    sealTokenId: bigint
  ];
  export interface OutputObject {
    donor: string;
    projectId: bigint;
    amount: bigint;
    wantsSeal: boolean;
    sealFee: bigint;
    timestamp: bigint;
    sealTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectAddedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    projectWallet: AddressLike
  ];
  export type OutputTuple = [projectId: bigint, projectWallet: string];
  export interface OutputObject {
    projectId: bigint;
    projectWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GhostFundDonation extends BaseContract {
  connect(runner?: ContractRunner | null): GhostFundDonation;
  waitForDeployment(): Promise<this>;

  interface: GhostFundDonationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addProject: TypedContractMethod<
    [_projectWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateSealFee: TypedContractMethod<
    [_donationAmount: BigNumberish],
    [bigint],
    "view"
  >;

  donate: TypedContractMethod<
    [_projectId: BigNumberish, _wantsSeal: boolean],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  projectCount: TypedContractMethod<[], [bigint], "view">;

  projects: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sealContract: TypedContractMethod<[], [string], "view">;

  sealFeeFixed: TypedContractMethod<[], [bigint], "view">;

  sealFeePercent: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFees: TypedContractMethod<
    [_fixed: BigNumberish, _percent: BigNumberish, _useFixed: boolean],
    [void],
    "nonpayable"
  >;

  useFixedFee: TypedContractMethod<[], [boolean], "view">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addProject"
  ): TypedContractMethod<[_projectWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateSealFee"
  ): TypedContractMethod<[_donationAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [_projectId: BigNumberish, _wantsSeal: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sealContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sealFeeFixed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sealFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFees"
  ): TypedContractMethod<
    [_fixed: BigNumberish, _percent: BigNumberish, _useFixed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useFixedFee"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DonationRecorded"
  ): TypedContractEvent<
    DonationRecordedEvent.InputTuple,
    DonationRecordedEvent.OutputTuple,
    DonationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectAdded"
  ): TypedContractEvent<
    ProjectAddedEvent.InputTuple,
    ProjectAddedEvent.OutputTuple,
    ProjectAddedEvent.OutputObject
  >;

  filters: {
    "DonationRecorded(address,uint256,uint256,bool,uint256,uint256,uint256)": TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;
    DonationRecorded: TypedContractEvent<
      DonationRecordedEvent.InputTuple,
      DonationRecordedEvent.OutputTuple,
      DonationRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProjectAdded(uint256,address)": TypedContractEvent<
      ProjectAddedEvent.InputTuple,
      ProjectAddedEvent.OutputTuple,
      ProjectAddedEvent.OutputObject
    >;
    ProjectAdded: TypedContractEvent<
      ProjectAddedEvent.InputTuple,
      ProjectAddedEvent.OutputTuple,
      ProjectAddedEvent.OutputObject
    >;
  };
}
