/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GhostFundReputationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "donationContract"
      | "getReputation"
      | "reputations"
      | "sealContract"
      | "updateReputation"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "donationContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sealContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "donationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sealContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export interface GhostFundReputation extends BaseContract {
  connect(runner?: ContractRunner | null): GhostFundReputation;
  waitForDeployment(): Promise<this>;

  interface: GhostFundReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  donationContract: TypedContractMethod<[], [string], "view">;

  getReputation: TypedContractMethod<
    [_donor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDonated: bigint;
        sealCount: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDonated: bigint;
        sealCount: bigint;
        lastDonationTimestamp: bigint;
      }
    ],
    "view"
  >;

  sealContract: TypedContractMethod<[], [string], "view">;

  updateReputation: TypedContractMethod<
    [_donor: AddressLike, _donationAmount: BigNumberish, _hasSeal: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "donationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [_donor: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDonated: bigint;
        sealCount: bigint;
        score: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalDonated: bigint;
        sealCount: bigint;
        lastDonationTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sealContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [_donor: AddressLike, _donationAmount: BigNumberish, _hasSeal: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
