/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GhostFundDonation } from "./GhostFundDonation";
export type { GhostFundPatronSeal } from "./GhostFundPatronSeal";
export type { GhostFundReputation } from "./GhostFundReputation";
